[profile.default]
  evm_version = "shanghai" # needed for greater coverage of EVM chains
  fs_permissions = [
    { access = "read", path = "package.json" },
  ]
  fuzz = { runs = 1000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.29"
  script = "scripts"
  src = "src"
  test = "tests"

# Compile only the production code and the test mocks with via IR
[profile.optimized]
  optimizer = true
  optimizer_runs = 100_000_000
  out = "out-optimized"
  test = "src"
  via_ir = true

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  # mainnets
  arbitrum = "https://arbitrum.drpc.org"
  avalanche = "https://avalanche.drpc.org"
  base = "https://mainnet.base.org"
  berachain = "https://rpc.berachain.com"
  blast = "https://rpc.blast.io"
  bsc = "https://binance.llamarpc.com"
  ethereum = "${MAINNET_RPC_URL}"
  chiliz = "https://rpc.chiliz.com"
  core_dao = "https://rpc.coredao.org"
  form = "https://rpc.form.network/http"
  gnosis = "https://gnosis.drpc.org"
  lightlink = "https://replicator.phoenix.lightlink.io/rpc/v1"
  linea = "https://rpc.linea.build"
  meld = "https://rpc-1.meld.com"
  mode = "https://mainnet.mode.network/"
  morph = "https://rpc.morphl2.io"
  optimism = "https://1rpc.io/op"
  polygon = "https://polygon.drpc.org"
  scroll = "https://rpc.scroll.io/"
  sei = "https://evm-rpc.sei-apis.com"
  superseed = "https://mainnet.superseed.xyz"
  xdc = "https://rpc.xdc.org"
  # testnets
  arbitrum_sepolia = "https://arbitrum-sepolia-rpc.publicnode.com"
  base_sepolia = "https://sepolia.base.org"
  berachain_artio = "https://bartio.rpc.berachain.com/"
  blast_sepolia = "https://sepolia.blast.io"
  linea_sepolia = "https://rpc.sepolia.linea.build"
  localhost = "http://localhost:8545"
  mode_sepolia = "https://sepolia.mode.network/"
  monat_testnet = "https://testnet-rpc.monad.xyz"
  morph_holesky = "https://rpc-holesky.morphl2.io"
  optimism_sepolia = "https://sepolia.optimism.io"
  sei_testnet = "https://evm-rpc.arctic-1.seinetwork.io"
  sepolia = "${SEPOLIA_RPC_URL}"
  superseed_sepolia = "https://sepolia.superseed.xyz"