[profile.default]
  ast = true                       # needed for upgrade safety validations by foundry-upgrades
  auto_detect_solc = false
  build_info = true                # needed for upgrade safety validations by foundry-upgrades
  bytecode_hash = "ipfs"
  evm_version = "shanghai"         # needed for greater coverage of EVM chains
  extra_output = ["storageLayout"] # needed for upgrade safety validations by foundry-upgrades
  fs_permissions = [
    { access = "read", path = "./out" },
    { access = "read", path = "./out-optimized" },
    { access = "read", path = "package.json" },
  ]
  ffi = true                        # needed for upgrade safety validations by foundry-upgrades
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "scripts"
  solc = "0.8.29"
  src = "src"
  test = "tests"

[profile.default.fuzz]
  max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail
  runs = 1000

[profile.default.invariant]
  call_override = false  # Override unsafe external calls to perform reentrancy checks
  depth = 100            # Number of calls executed in one run
  fail_on_revert = true
  runs = 200
  show_metrics = false

# Compile only the production code and the test mocks with via IR
[profile.optimized]
  optimizer = true
  optimizer_runs = 100_000_000
  out = "out-optimized"
  test = "src"
  via_ir = true

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[lint]
  lint_on_build = false

[rpc_endpoints]
  # mainnets
  arbitrum = "https://lb.routeme.sh/rpc/42161/${ROUTEMESH_API_KEY}"
  avalanche = "https://lb.routeme.sh/rpc/43114/${ROUTEMESH_API_KEY}"
  base = "https://lb.routeme.sh/rpc/8453/${ROUTEMESH_API_KEY}"
  berachain = "https://lb.routeme.sh/rpc/80094/${ROUTEMESH_API_KEY}"
  blast = "https://lb.routeme.sh/rpc/81457/${ROUTEMESH_API_KEY}"
  bsc = "https://lb.routeme.sh/rpc/56/${ROUTEMESH_API_KEY}"
  ethereum = "https://lb.routeme.sh/rpc/1/${ROUTEMESH_API_KEY}"
  chiliz = "https://lb.routeme.sh/rpc/88888/${ROUTEMESH_API_KEY}"
  core_dao = "https://lb.routeme.sh/rpc/1116/${ROUTEMESH_API_KEY}"
  form = "https://lb.routeme.sh/rpc/478/${ROUTEMESH_API_KEY}"
  gnosis = "https://lb.routeme.sh/rpc/100/${ROUTEMESH_API_KEY}"
  lightlink = "https://lb.routeme.sh/rpc/1890/${ROUTEMESH_API_KEY}"
  linea = "https://lb.routeme.sh/rpc/59144/${ROUTEMESH_API_KEY}"
  meld = "https://rpc-1.meld.com"
  mode = "https://lb.routeme.sh/rpc/34443/${ROUTEMESH_API_KEY}"
  morph = "https://lb.routeme.sh/rpc/2818/${ROUTEMESH_API_KEY}"
  optimism = "https://lb.routeme.sh/rpc/10/${ROUTEMESH_API_KEY}"
  polygon = "https://lb.routeme.sh/rpc/137/${ROUTEMESH_API_KEY}"
  scroll = "https://lb.routeme.sh/rpc/534352/${ROUTEMESH_API_KEY}"
  sei = "https://lb.routeme.sh/rpc/1329/${ROUTEMESH_API_KEY}"
  superseed = "https://lb.routeme.sh/rpc/5330/${ROUTEMESH_API_KEY}"
  xdc = "https://lb.routeme.sh/rpc/50/${ROUTEMESH_API_KEY}"
  # testnets
  arbitrum_sepolia = "https://lb.routeme.sh/rpc/421614/${ROUTEMESH_API_KEY}"
  base_sepolia = "https://lb.routeme.sh/rpc/84532/${ROUTEMESH_API_KEY}"
  blast_sepolia = "https://lb.routeme.sh/rpc/168587773/${ROUTEMESH_API_KEY}"
  linea_sepolia = "https://lb.routeme.sh/rpc/59141/${ROUTEMESH_API_KEY}"
  localhost = "http://localhost:8545"
  mode_sepolia = "https://lb.routeme.sh/rpc/919/${ROUTEMESH_API_KEY}"
  monad_testnet = "https://lb.routeme.sh/rpc/10143/${ROUTEMESH_API_KEY}"
  optimism_sepolia = "https://lb.routeme.sh/rpc/11155420/${ROUTEMESH_API_KEY}"
  sei_testnet = "https://lb.routeme.sh/rpc/713715/${ROUTEMESH_API_KEY}"
  sepolia = "https://lb.routeme.sh/rpc/11155111/${ROUTEMESH_API_KEY}"
  superseed_sepolia = "https://sepolia.superseed.xyz"
