[profile.default]
  evm_version = "shanghai" # needed for greater coverage of EVM chains
  fs_permissions = [
    { access = "read", path = "package.json" },
  ]
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.29"
  script = "scripts"
  src = "src"
  test = "tests"

# Compile only the production code and the test mocks with via IR
[profile.optimized]
  optimizer = true
  optimizer_runs = 100_000_000
  out = "out-optimized"
  test = "src"
  via_ir = true

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
  avalanche = "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}"
  base = "https://mainnet.base.org"
  gnosis = "https://rpc.gnosischain.com"
  linea = "https://rpc.linea.build"
  mainnet = "https://mainnet.infura.io/v3/${API_KEY_INFURA}"
  optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
  polygon = "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}"
  scroll = "https://rpc.scroll.io/"
  sepolia = "${SEPOLIA_RPC_URL}"