name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@main"

  bulloak:
    needs: ["lint"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/bulloak-check.yml@main"
    with:
      skip-modifiers: true
      tree-path: "tests"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@main"

  test-unit:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      match-path: "tests/**/*.sol"
      name: "Unit tests"

  coverage:
    needs: ["lint", "build"]
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-coverage.yml@main"
    with:
      match-path: "tests/**/*.sol"
      via-ir-minimum: true
